<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIuvvx5g\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIuvvx5g/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIuvvx5g.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIuvvx5g\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIuvvx5g\appProdProjectContainer([
    'container.build_hash' => 'Iuvvx5g',
    'container.build_id' => 'a58c9683',
    'container.build_time' => 1578652763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIuvvx5g');
