<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjhd9bh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjhd9bh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFjhd9bh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFjhd9bh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFjhd9bh\appDevDebugProjectContainer([
    'container.build_hash' => 'Fjhd9bh',
    'container.build_id' => '5df818fd',
    'container.build_time' => 1576165419,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFjhd9bh');
